// @ts-nocheck
// /components/schedule/timeline/sampleData.ts
import { Schedule, Member } from "@/types/schedule";

export const sampleMembers: Member[] = [
  { id: 1, name: "田中" },
  { id: 2, name: "佐藤" },
  { id: 3, name: "鈴木" },
  { id: 4, name: "高橁E },
  { id: 5, name: "伊藤" },
];

export const sampleSchedules: Schedule[] = [
  // 田中
  {
    id: 1,
    memberId: 1,
    start: "06:30",
    end: "08:00",
    flag: "事務所",
    project: "案件A",
    notes: "早朝賁E��整琁E,
    slotIndex: 0,
    slotCount: 1,
  },
  {
    id: 2,
    memberId: 1,
    start: "08:30",
    end: "10:00",
    flag: "現場",
    project: "案件B",
    notes: "現場立会い",
    slotIndex: 0,
    slotCount: 2,
  },
  {
    id: 3,
    memberId: 1,
    start: "09:00",
    end: "10:30",
    flag: "打ち合わぁE,
    project: "案件C",
    notes: "設計レビュー",
    slotIndex: 1,
    slotCount: 2,
  },
  {
    id: 4,
    memberId: 1,
    start: "11:00",
    end: "13:00",
    flag: "事務所",
    project: "案件D",
    notes: "賁E��作�E",
    slotIndex: 0,
    slotCount: 1,
  },
  {
    id: 5,
    memberId: 1,
    start: "14:00",
    end: "17:00",
    flag: "打ち合わぁE,
    project: "案件E",
    notes: "顧客定例企E,
    slotIndex: 0,
    slotCount: 1,
  },
  {
    id: 6,
    memberId: 1,
    start: "19:00",
    end: "21:30",
    flag: "現場",
    project: "案件F",
    notes: "夜間現場確誁E,
    slotIndex: 0,
    slotCount: 1,
  },

  // 佐藤
  {
    id: 7,
    memberId: 2,
    start: "07:00",
    end: "08:30",
    flag: "事務所",
    project: "案件G",
    notes: "朝会賁E��作�E",
    slotIndex: 0,
    slotCount: 1,
  },
  {
    id: 8,
    memberId: 2,
    start: "09:00",
    end: "11:00",
    flag: "打ち合わぁE,
    project: "案件H",
    notes: "社冁E��ーチE��ング",
    slotIndex: 0,
    slotCount: 1,
  },
  {
    id: 9,
    memberId: 2,
    start: "11:30",
    end: "13:00",
    flag: "現場",
    project: "案件I",
    notes: "現場点椁E,
    slotIndex: 0,
    slotCount: 1,
  },
  {
    id: 10,
    memberId: 2,
    start: "14:00",
    end: "17:00",
    flag: "事務所",
    project: "案件J",
    notes: "提案賁E��作�E",
    slotIndex: 0,
    slotCount: 1,
  },
  {
    id: 11,
    memberId: 2,
    start: "18:00",
    end: "20:00",
    flag: "打ち合わぁE,
    project: "案件K",
    notes: "顧客対忁E,
    slotIndex: 0,
    slotCount: 1,
  },

  // 鈴木
  {
    id: 12,
    memberId: 3,
    start: "06:00",
    end: "07:30",
    flag: "事務所",
    project: "案件L",
    notes: "メール対忁E,
    slotIndex: 0,
    slotCount: 1,
  },
  {
    id: 13,
    memberId: 3,
    start: "08:00",
    end: "10:00",
    flag: "打ち合わぁE,
    project: "案件M",
    notes: "チ�EムMTG",
    slotIndex: 0,
    slotCount: 2,
  },
  {
    id: 14,
    memberId: 3,
    start: "09:30",
    end: "11:00",
    flag: "現場",
    project: "案件N",
    notes: "現場確誁E,
    slotIndex: 1,
    slotCount: 2,
  },
  {
    id: 15,
    memberId: 3,
    start: "13:00",
    end: "15:00",
    flag: "事務所",
    project: "案件O",
    notes: "設計書作�E",
    slotIndex: 0,
    slotCount: 1,
  },
  {
    id: 16,
    memberId: 3,
    start: "17:00",
    end: "19:30",
    flag: "打ち合わぁE,
    project: "案件P",
    notes: "外部協議",
    slotIndex: 0,
    slotCount: 1,
  },

  // 高橁E
  {
    id: 17,
    memberId: 4,
    start: "07:30",
    end: "09:00",
    flag: "事務所",
    project: "案件Q",
    notes: "チE��イン調整",
    slotIndex: 0,
    slotCount: 1,
  },
  {
    id: 18,
    memberId: 4,
    start: "10:00",
    end: "12:00",
    flag: "打ち合わぁE,
    project: "案件R",
    notes: "クライアンチETG",
    slotIndex: 0,
    slotCount: 1,
  },
  {
    id: 19,
    memberId: 4,
    start: "13:30",
    end: "15:30",
    flag: "現場",
    project: "案件S",
    notes: "現場ヒアリング",
    slotIndex: 0,
    slotCount: 1,
  },
  {
    id: 20,
    memberId: 4,
    start: "16:00",
    end: "18:00",
    flag: "事務所",
    project: "案件T",
    notes: "社冁E��E��更新",
    slotIndex: 0,
    slotCount: 1,
  },
  {
    id: 21,
    memberId: 4,
    start: "20:00",
    end: "22:00",
    flag: "打ち合わぁE,
    project: "案件U",
    notes: "夜間会議",
    slotIndex: 0,
    slotCount: 1,
  },

  // 伊藤
  {
    id: 22,
    memberId: 5,
    start: "06:00",
    end: "08:00",
    flag: "事務所",
    project: "案件V",
    notes: "朝作業",
    slotIndex: 0,
    slotCount: 1,
  },
  {
    id: 23,
    memberId: 5,
    start: "09:00",
    end: "11:30",
    flag: "現場",
    project: "案件W",
    notes: "現場点椁E,
    slotIndex: 0,
    slotCount: 1,
  },
  {
    id: 24,
    memberId: 5,
    start: "13:00",
    end: "16:00",
    flag: "打ち合わぁE,
    project: "案件X",
    notes: "顧客ヒアリング",
    slotIndex: 0,
    slotCount: 1,
  },
  {
    id: 25,
    memberId: 5,
    start: "17:00",
    end: "20:00",
    flag: "事務所",
    project: "案件Y",
    notes: "チE�Eタ雁E��E,
    slotIndex: 0,
    slotCount: 1,
  },
];

